name: 📷 Hadřík bot
on:
  push:
    paths:
      - '**logo.png'
  workflow_dispatch:
jobs:
  generate-favicon:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
      
      - name: Print hello world
        run: |
          cd public\asstes
          convert logo.png -resize 96x96 logo.png
          echo 'World'
